import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-aboutus-content',
  templateUrl: './aboutus-content.component.html',
  styleUrls: ['./aboutus-content.component.css']
})
export class AboutusContentComponent implements OnInit {

  comments = [
    {comment: "Ankara Anadolu Güzel Sanatlar Lisesi’nden mezun olduktan sonra Gazi Üniversitesi Müzik Eğitimi Anabilim Dalı’nda öğrenimine devam etti. Üniversite öğrenimi devam ederken Liz Teyze’nin mirasını yaşatan LERA’da birçok uzun ve kısa süreli Orff-Schulwerk ve Drama kursuna katıldı. 2005 yılında Üniversiteden mezun olmasının ardından Hacettepe Üniversitesi Eğitim Fakültesi Okul Öncesi Eğitimi Bölümü’nde tezsiz yüksek lisans statüsünde özel öğrenci olarak okudu. 2005 yılında Ankara’da çeşitli okul öncesi eğitim kurumlarında müzik öğretmenliğine başladı. 2008-2009 yılları arasında The Special Course: Advanced Studies In Music And Dance Education – Orff- Schulwerk olarak adlandırılan lisansüstü eğitim programını tamamladı. 2005-2015 yılları arasında birçok özel kurumda müzik öğretmenliği ve piyano öğretmenliği yaptıktan sonra 2016 yılında oğlu Geceyi kucağına aldı ve öğretmenliğe ara verdi. 2019 yılının başından beri ORFFDER için çalışmaktadır.", show: false},
    {comment: "1992 yılında İstanbul Teknik Üniversitesi Türk Müziği Devlet Konservatuarından mezun oldu. Aynı üniversitede 1992-1994 yılları arasında aynı üniversitede sosyal bilimler enstitüsünde yüksek lisansını tamamladı. Marmara Üniversitesi İşletme Fakültesi iktisat Bölümü’nde iktisat alanında 2. yüksek lisansını tamamladı. Şu anda aynı konu üzerine Beykent Üniversitesinde İşletme Yönetimi Bölümü’nde doktora öğrencisidir. Müzik alanının kurumsal işleyiş açısından nasıl başarılı ve etkin var olabileceği üzerine düşünerek, eğitimde verimlilik ve sürdürülebilirlik konuları üzerine çalıştı. Okul Öncesi Dönemde Müzik Eğitimi konulu yüksek lisans tezi sırasında müzik eğitiminin çok küçük yaşlardan doğru temellendirilmesi gerekliliğine inandı ve bu noktadan yola çıkarak 2000 yılından itibaren Orff-Schulwerk pedagojisi üzerine çalışmaya başladı. Birçok ulusal ve uluslararası Orff-Schulwerk eğitimini takip etti. Avusturya, Macaristan ve Amerika’daki yaz kurslarında bulundu, Türkiye’deki Level kursları ve The International San Francisco Orff-Schulwerk Certification Level 1-2 eğitimlerini tamamladı. Mimar Sinan Güzel Sanatlar Üniversitesi Dans ve Hareket Terapisi eğitim programını tamamladı. Çalışmalarına hareket terapisi, sanat terapisi, masal terapisi gibi farklı alanlardan da beslenerek devam etmekte, aynı zamanda vurmalı çalgılar üzerine çalışmakta ve çocuklara uygun hazırlanmış eğitim programlarında eğitim vermektedir. 25 yıldır devlet okullarında müzik öğretmenliği yapmakta olup halen Galatasaray İlkokulu ve Ortaokulu’nda müzik öğretmeni olarak görev yapmaktadır.", show: false},
    {comment: "1997'de Marmara Üniversitesi Müzik Eğitimi Bölümü’nden mezun oldu. Aynı yıl özel Ahmet Şimşek Koleji'nde müzik öğretmeni olarak çalışmaya başladı. 2013 yılından beri özel eğitim kurumu Türkan Sabancı Görme Engelliler Okulu’nda çalışmaktadır. Bu kurumda yetenekli görme engelli ve çok engelli çocuklar için çalgı eğitim dersleri açtı, bu öğrencilerini güzel sanatlar liselerine ve üniversitelerin müzik eğitimi bölümlerine yerleştirdi. Görme engelli öğrencileri ile TÜBİTAK projelerine katıldı. M.E.B materyal geliştirme projelerinde materyaller tasarladı. 2007-2008 yıllarında Okay Temiz Ritim Atölyesi'nde eğitimlere katıldı. 2016-2019 yılları arasında birçok ulusal ve uluslararası Orff-Schulwerk eğitimine katıldı. 2018 yılında Mozarteum Üniversitesi Orff Enstitüsü'nün Orff-Schulwerk Elementer Müzik ve Dans Pedagojisi Yaz Kursu’na katıldı. İlk defa görme engellilerle Beden Perküsyonu ile Ninnilerimiz, Beden Perküsyonu ve Bardak Ritim ile Türkülerimiz konserlerini düzenledi. Bu çalışmalardan bir tanesi de yakın tarihte Carl Orff Vakfı'nın YouTube resmi kanalında yayınlandı. 2017 yılında Bahçeşehir Üniversitesi Uluslararası Müzik Terapi Sempozyumu’na katıldı. 2018-2019 yılında Medipol Üniversitesi GETAT Müzik Terapi Sertifika Eğitimi’ne katıldı. Ardından müzik terapisi alanında İstanbul Milli Eğitim Müdürlüğü’nün hazırlamış olduğu Öğretmenim Elimi Tut adlı projenin çalıştayına katıldı. 2019 yılında Marmara Üniversitesi 2. Kodaly Eğitim Günleri programına katıldı. Özel eğitimde görme engellilere yönelik çalgı eğitimi ve müzik eğitimi öğrenim modelleri geliştirmeye devam etmekte, aynı zamanda Fatih Sultan Mehmet Vakıf Üniversitesi Okul Öncesi Öğretmenliği Bölümü'nde Erken Çocuklukta Müzik dersleri vermektedir.", show: false},
    {comment: "Dokuz Eylül Üniversitesi Buca Eğitim Fakültesi Müzik Öğretmenliğinden mezun olduktan sonra yüksek lisansını Yeditepe Üniversitesi Güzel Sanat Fakültesi’nde Sanat Yönetimi üstünde tamamladı. Birçok sanatsal projede ve proje yönetiminde proje yöneticisi olarak yer aldı.  2011’de Ordu Kumru’da öğretmenlik hayatına başladı. Çalıştığı okulda Orff-Schulwerk uygulamalarına uygun müzik sınıfı kurarak bu alanda çocuklar ile çalışmalarına ağırlık verdi. 2011-2014’de özel eğitim bursuyla The International San Francisco Orff-Schulwerk Certification programını tamamladı. Bunun yanında 2011’de Holy Names University Kodaly Institute’de Level-1 eğitimini tamamladı. Birçok ulusal ve uluslararası Orff-Schulwerk eğitimine katıldı. Şu an İstanbul’da bir devlet okulunda öğretmenlik serüvenine devam etmektedir ve çeşitli eğitim, sosyal sorumluluk projelerinde aktif olarak yer almaktadır.", show: false},
    {comment: "İstanbul Yıldız Teknik Üniversitesi Sanat ve Tasarım Fakültesi Duysal Tasarım Programı Müzikoloji Bölümü’nden 2005 yılında mezun oldu ve uzun yıllar Nuri Candaş, Yıldız Dağdelen, Şebnem Ünal ve Remziye Alper gibi önemli hocalardan opera ve şan eğitimi aldı. Salzburg'daki Mozarteum Üniversitesi Orff Enstitüsü'nde önce bir yıl misafir öğrenci olarak eğitim aldı daha sonra The Special Course: Advanced Studies In Music And Dance Education – Orff- Schulwerk olarak adlandırılan lisansüstü eğitim programını tamamladı ve en son olarak da 2008 yılında aynı üniversiteden Elementer Müzik ve Hareket Pedagojisi mastır derecesini aldı. 2008-2010 yılları arasında yine Mozarteum Üniversitesi Orff-Enstitüsü'nde Ebeveyn Çocuk Grubu adlı dersleri verdi. 2009-2012 yılları arasında Avusturya Orff-Schulwerk Derneği´nin in başkan yardımcılığını yaptı. Almanya’nın önde gelen müzik eğitimi yayın serilerinden olan ve 2013 yılında Schott Yayınevi tarafından yayımlanan Musik voraus- Musik und Tanz für Kinder, Unterrichtswerk für Kinder von 6 bis 8 (Haydi Müziğe – Çocuklar için Müzik ve Dans. 6-8 Yaş Çocuklar için Ders Kitabı) adlı eserin yazarları arasında yer aldı. Bunların yanında uzun yıllar hem Avusturya´daki hem de Almanya`daki okullarda ve aralarında önemli ödüller almış olan çeşitli müzik eğitimi projelerinde müzik ve hareket pedagogu olarak çalıştı, çok sayıda öğretmen eğitimi kursları verdi. Aralık 2018´de Orff-Schulwerk: Elementer Müzik ve Hareket Pedagojisinin Temelleri adlı kitabı Pan Yayıncılık tarafından yayımlandı. Aynı kitabın Almancası Haziran 2018'de ve İngilizcesi 2019 yılında yine Almanya’nın en önde gelen yayıncılarından olan Schott Yayınevi tarafından yayımlandı. Bir süre Bamberg Otto-Friedrich-Üniversitesi Müzik Pedagojisi ve Müzik Öğretimi Bölümü´nde öğretim üyeliği yaptı. Halen Elementer Müzik ve Hareket Pedagojisi alanında birçok kitap projesi üzerinde çalışmakta, ulusal ve uluslararası alanda seminerler ve kurslar vermekte ve Nürnberg Müzik Üniversitesi Elementer Müzik Pedagojisi Bölümü´nde öğretim üyeliği yapmaktadır. 2020-2021 eğitim öğretim yılından itibaren Salzburg'daki Mozarteum Üniversitesi Orff Enstitüsü´nde The Special Course: Advanced Studies In Music And Dance Education – Orff- Schulwerk lisansüstü eğitim programında ders vermeye başlayacaktır. ", show: false},
    {comment: "1998 yılında Marmara Üniversitesi Müzik Eğitimi Bölümü’nden mezun oldu. 2001 yılında Özel Alev Okulları’nda müzik öğretmenliğine başladı. Orff çalgıları ürettiği ve pedagojik çalgı yapım eğitimleri verdiği Kendin Yap Kendin Çal Atölyesi’ni kurdu. Türkiye’nin 30 farklı şehrinde eğitimcilere yönelik birçok uygulamalı seminer verdi. Salzburg'daki Mozarteum Üniversitesi Orff Enstitüsü'nde düzenlenen uluslararası yaz kurslarında eğitmenlik yapan Erol; aynı üniversitede 1 yıl süreyle eğitim gördü.  Avusturya Orff Schulwerk Forum ve Orff Geselshaft’ dan “Train the Trainer” belgesi, ABD San Francisco School’dan Orff Level-3 derecesi aldı. Karamela Sepeti, Müzikolaj, Şarkı Söyle Dans Et, Kendin Yap Kendin Çal ve Çikolata adlı kitapları, aynı isimlerde çocuk şarkıları albümleri yayınlandı. 2015’te kendi yazdığı çocuk şarkılarının videolarından oluşan Karamela Sepeti adlı 150 bin aboneli YouTube kanalını kurdu. Onur Erol halen Orff-Schulwerk alanında eğitimcilik yapmakta ve çocuklar, aileler ve öğretmenler için içerikler üretmektedir. ", show: false},
    {comment: "2005-2006 eğitim yılında Londra University of Surrey Roehampton Film Studies ve Early Childhood Studies bölümlerinden mezun oldu. 2005 yaz döneminde Salzburg Mozarteum Üniversitesi’nde Orff-Schulwerk eğitimine katıldı. Ocak 2007 de Ezo Sunal Çocuk Atölyesi’ni kurdu. 2008 yaz döneminde Asociacion Orff-España tarafından düzenlenen MÚSICA Y DANZA EN LA EDUCACIÓN başlığındaki uluslararası yaz kursuna katıldı. 2010-2013 yılları arasında Her Beden Duyar projesi kapsamında, Anadolu Üniversitesi Engelli Entegre Yüksek Okulu’ndan işitme engelli gençlerle beden perküsyonu çalışmalarını gerçekleştirdi. 2010 yılında Brezilya Sao Paulo, 2011 yılında ABD San Francisco, 2012 yılında İstanbul, 2013 yılında San Francisco’ da gerçekleşen Uluslararası Beden Müziği Festivallerine katıldı. 2010-2014 yılları arasında Akbank Caz Festivali kapsamında çocuk atölyeleri düzenledi. 2011-2012 yılları arasında AK Sanat’ ta Çocuklarla Orff Yaklaşımı ile Hareket ve Müzik atölyeleri düzenledi. 2013-2016 eğitim yılları arasında Okan Üniversitesi Çocuk Gelişimi Bölümü’nde Çocuk ve Müzik alanında ders verdi. Amerika´daki The International San Francisco Orff-Schulwerk Levels I,II,III Certification Program eğitimlerini 2013 yılında tamamladı. 2017 yılında okul öncesi ve ilköğretim çağındaki çocuklar için orijinal şarkılar, hikayeler, oyunlar ve aktivite fikirleri sunan LALALA isimli mobil aplikasyonu ve LALALA Dünyası adıyla bir YouTube kanalı kurdu. 2018 yılında LALALA şarkılarını sahneye taşıyarak LALALA Konserleri’ni vermeye başladı. Kes Yapıştır Kendin Yap, Karnı Acıkan Kedi, Uykusu Kaçan Kaplumbağa, Kabuğuna Sığmayan Yengeç kitapları yazdı. Halen atölye ve beden perküsyonu alanındaki çalışmalarının yanı sıra, öğretmen seminerleri düzenlemekte, özel kurumlara eğitimler hazırlayıp uygulamakta, çeşitli çocuk atölyelerinde ve kurucusu olduğu Ezo Sunal Çocuk Atölyesi’nde eğitmen olarak görev almaktadır.", show: false},

  ]

  constructor() { }

  ngOnInit() {
  }

  getComment(review: {comment:string,show:boolean}){
    if(review.show){
      return review.comment;
    }else{
      var text = review.comment.substring(0,635);
      const seperatedText = text.split(" ");
      const lastText = seperatedText.slice(-1).pop();
      return text.substring(0, text.length - lastText.length);
    }
  }

  openTuzuk(){
    var win = window.open('/assets/pdf/tüzük.pdf', '_blank');
    win.focus();
  }
}
